### ISSUE TITLE
java.lang.Exception: ebRequireJava6 := true

### ISSUE THREAD

**Issue by glidester** [sqs/sbt-elasticbeanstalk#9]
Hitting some issues whist trying to configure sbt-elasticbeanstalk in my play 2.2 application.

When I run eb-deploy it errors:

```
[trace] Stack trace suppressed: run last *:ebUploadSourceBundle for the full output.
[error] (*:ebUploadSourceBundle) java.lang.Exception: ebRequireJava6 := true, but you are currently running in Java 1.7. As of Dec 2012, Elastic Beanstalk is incompatible with Java7. You should use Java6 to compile and deploy WARs. You can also set ebRequireJava6 := false in your sbt settings to suppress this warning, but beware that Java7-compiled WARs currently fail in strange ways on Elastic Beanstalk. See http://qslack.com/2012/12/using-java-1-7-on-amazon-aws-elastic-beanstalk/ for a workaround.
[error] Total time: 5 s, completed 12-Nov-2014 15:02:24
```

I am using Java 1.8.0_20 so not sure this message is relevant. Anyway, I added the suggested "ebRequireJava6 := false" to my config so:

```
val main = play.Project(appName, appVersion, appDependencies)
    .settings(
      Play2WarKeys.servletVersion := "3.0",
      ebRequireJava6 := false,
      ebAppBundle <<= Play2WarKeys.war,
      ebS3BucketName := "elasticbeanstalk-eu-west-1-449979607234",
      ebDeployments := Seq(
        Deployment(
          "upgrade-service",
          envBaseName = "upgradeservice",
          templateName = "my-template",
          cname = "upservaccountz",
          environmentVariables = Map("MyFavoriteColor" -> "blue"),
          solutionStackName = "Java"
        )
      ),
      ebRegion := "eu-west-1"
    )
    .settings(Play2WarPlugin.play2WarSettings: _*)
    .settings(ElasticBeanstalk.elasticBeanstalkSettings: _*)
    .settings(
        javaOptions in Test += "-Dconfig.file=conf/application-dev.conf"
    )
```

but I still see the same error message.

Am I doing something wrong or is there a bug?

Thanks

Tim

**Comment by glidester** [comment]
Ok, as a hacky work around I added 

```
System.setProperty("java.specification.version","1.6")
```

to my Build.scala

**Comment by glidester** [comment]
Poking around I think I might of found the issue in class com.joescii.sbtelasticbeanstalk.ElasticBeanstalkSettings line 40:

```
ebRequireJava6 := true
```

seems to hard-code this value rather than taking the specified value.

I came across this by accident while trying to solve another issue, that of my exiting app environment name being longer than the "(23 -7)" allowed. I'm assuming you can deploy to an existing environment and that you don't have to create a new one each time.

**Comment by joescii** [comment]
You're hitting some of the unfinished edges. :)  I've thought about ditching that require Java 6 property because I don't think it matters any more, but I've been happily circumventing it for a while now.  I've also grown accustomed to the warnings about deploying to an existing environment.  It's those sorts of things that sit on the todo list until you delete the app, ya know?

**Comment by glidester** [comment]
It seems deploying to an existing environment is not possible because your username +rand is always added to the envBaseName specified making a new unique environment name (so you can't specify an existing env). 

I've tried to compile my own version of the code but I can't seem to get sbt to pickup my custom jar even with the "sbtPlugin := true" setting and the custom jar in my project's lib folder. Any pointers developing custom sbt plugins?

Cheers,

Tim

**Comment by joescii** [comment]
Hey Tim,

I missed your last statement the first time regarding deploying to the same environment.  You can configure the plugin to do so, but it's not obvious how.  You have to provide another function for the `ebEnvironmentNameSuffix` key.  I _think_ the following will accomplish what you are looking for:

``` scala
ebEnvironmentNameSuffix := (_ => "static-name") 
```

If you still want to build your own version, the best way to get it into another project is the run the `publishLocal` task in the plugin project.  This will make it available in your local `.ivy` repo for your other project to pickup.  Otherwise, you should probably put the jar in the `project/lib` directory.

**Comment by glidester** [comment]
Thanks for the info Joescii. 

I'll try and give it a go if I get some free time. I've ended up writing some bash deployment scripts that use the aws and eb cli commands. I need to dig into sbt more to really figure out how to configure it to do what I need.
